### ISSUE TITLE
ImportError: cannot import name 'deform_conv_cuda'

### ISSUE THREAD

**Issue by songjiechong** [JimmyChame/SADNet#1]
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    from model.__init__ import make_model
  File "/userhome/sjc/SADNet/model/__init__.py", line 1, in <module>
    from model.sadnet import SADNET
  File "/userhome/sjc/SADNet/model/sadnet.py", line 6, in <module>
    from dcn.deform_conv import ModulatedDeformConvPack2 as DCN
  File "/userhome/sjc/SADNet/dcn/__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv, ModulatedDeformConvPack,
  File "/userhome/sjc/SADNet/dcn/deform_conv.py", line 10, in <module>
    from . import deform_conv_cuda
ImportError: cannot import name 'deform_conv_cuda'

**Comment by JimmyChame** [comment]
You may recompile the dcn module according to your machine and then replace deform_conv.py with our file.
