### ISSUE TITLE
Issue when I run test.py

### ISSUE THREAD

**Issue by luckydog1996** [JimmyChame/SADNet#4]
Traceback (most recent call last):
  File "/home/ztzhao/Documents/code/papers/SADNet/model/sadnet.py", line 7, in <module>
    from dcn.deform_conv import ModulatedDeformConvPack2 as DCN
  File "/home/ztzhao/Documents/code/papers/SADNet/dcn/__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv, ModulatedDeformConvPack,
  File "/home/ztzhao/Documents/code/papers/SADNet/dcn/deform_conv.py", line 10, in <module>
    from . import deform_conv_cuda
ImportError: cannot import name 'deform_conv_cuda' from 'dcn' (/home/ztzhao/Documents/code/papers/SADNet/dcn/__init__.py)

**Comment by JimmyChame** [comment]
You may recompile the dcn module according to your machine and then replace deform_conv.py with our file.

**Comment by luckydog1996** [comment]
Sorry, I am not familiar with .cpp or .cuda. May you kindly show more detailed instructions on how to "compile"?

**Comment by JimmyChame** [comment]
You can compile the code according to your machine.
```
cd ./dcn
python setup.py develop
```
